//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BJAirQuality
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TB_Message", Namespace="http://schemas.datacontract.org/2004/07/BJAirQuality", IsReference=true)]
    public partial class TB_Message : System.Data.Objects.DataClasses.EntityObject
    {
        
        private string AQIField;
        
        private System.DateTime Date_TimeField;
        
        private string DescriptionField;
        
        private int IDField;
        
        private string PriPollutantField;
        
        private string PromptField;
        
        private string QLevelField;
        
        private string QualityField;
        
        private string zoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AQI
        {
            get
            {
                return this.AQIField;
            }
            set
            {
                this.AQIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_Time
        {
            get
            {
                return this.Date_TimeField;
            }
            set
            {
                this.Date_TimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriPollutant
        {
            get
            {
                return this.PriPollutantField;
            }
            set
            {
                this.PriPollutantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prompt
        {
            get
            {
                return this.PromptField;
            }
            set
            {
                this.PromptField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QLevel
        {
            get
            {
                return this.QLevelField;
            }
            set
            {
                this.QLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Quality
        {
            get
            {
                return this.QualityField;
            }
            set
            {
                this.QualityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string zone
        {
            get
            {
                return this.zoneField;
            }
            set
            {
                this.zoneField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TB_RTC", Namespace="http://schemas.datacontract.org/2004/07/BJAirQuality", IsReference=true)]
    public partial class TB_RTC : System.Data.Objects.DataClasses.EntityObject
    {
        
        private string AQIField;
        
        private System.Nullable<float> AVG24hField;
        
        private System.DateTime Date_TimeField;
        
        private System.Nullable<int> Day8hMaxEvalField;
        
        private System.Nullable<float> Day8hMaxValueField;
        
        private System.Nullable<float> Day8hValueField;
        
        private System.Nullable<int> DayMaxEvalField;
        
        private System.Nullable<float> DayMaxValueField;
        
        private System.Nullable<int> EvalField;
        
        private System.Nullable<int> Eval24hField;
        
        private int IDField;
        
        private string PollutantField;
        
        private string PriPollutantField;
        
        private string PriPollutantMobileField;
        
        private string QLevelField;
        
        private string QualityField;
        
        private string StationField;
        
        private System.Nullable<float> ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AQI
        {
            get
            {
                return this.AQIField;
            }
            set
            {
                this.AQIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> AVG24h
        {
            get
            {
                return this.AVG24hField;
            }
            set
            {
                this.AVG24hField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_Time
        {
            get
            {
                return this.Date_TimeField;
            }
            set
            {
                this.Date_TimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Day8hMaxEval
        {
            get
            {
                return this.Day8hMaxEvalField;
            }
            set
            {
                this.Day8hMaxEvalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> Day8hMaxValue
        {
            get
            {
                return this.Day8hMaxValueField;
            }
            set
            {
                this.Day8hMaxValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> Day8hValue
        {
            get
            {
                return this.Day8hValueField;
            }
            set
            {
                this.Day8hValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DayMaxEval
        {
            get
            {
                return this.DayMaxEvalField;
            }
            set
            {
                this.DayMaxEvalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> DayMaxValue
        {
            get
            {
                return this.DayMaxValueField;
            }
            set
            {
                this.DayMaxValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Eval
        {
            get
            {
                return this.EvalField;
            }
            set
            {
                this.EvalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Eval24h
        {
            get
            {
                return this.Eval24hField;
            }
            set
            {
                this.Eval24hField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pollutant
        {
            get
            {
                return this.PollutantField;
            }
            set
            {
                this.PollutantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriPollutant
        {
            get
            {
                return this.PriPollutantField;
            }
            set
            {
                this.PriPollutantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriPollutantMobile
        {
            get
            {
                return this.PriPollutantMobileField;
            }
            set
            {
                this.PriPollutantMobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QLevel
        {
            get
            {
                return this.QLevelField;
            }
            set
            {
                this.QLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Quality
        {
            get
            {
                return this.QualityField;
            }
            set
            {
                this.QualityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Station
        {
            get
            {
                return this.StationField;
            }
            set
            {
                this.StationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<float> Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TB_Alert", Namespace="http://schemas.datacontract.org/2004/07/BJAirQuality", IsReference=true)]
    public partial class TB_Alert : System.Data.Objects.DataClasses.EntityObject
    {
        
        private System.DateTime Date_TimeField;
        
        private int IDField;
        
        private string MContentField;
        
        private string PublisherField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_Time
        {
            get
            {
                return this.Date_TimeField;
            }
            set
            {
                this.Date_TimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MContent
        {
            get
            {
                return this.MContentField;
            }
            set
            {
                this.MContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Publisher
        {
            get
            {
                return this.PublisherField;
            }
            set
            {
                this.PublisherField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
}
namespace System.Data.Objects.DataClasses
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BJAirQuality.TB_RTC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BJAirQuality.TB_Alert))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BJAirQuality.TB_Message))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BJAirQuality.TB_RTC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BJAirQuality.TB_Alert))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BJAirQuality.TB_Message))]
    public partial class EntityObject : System.Data.Objects.DataClasses.StructuralObject
    {
        
        private System.Data.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.EntityKey EntityKey
        {
            get
            {
                return this.EntityKeyField;
            }
            set
            {
                this.EntityKeyField = value;
            }
        }
    }
}
namespace System.Data
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    public partial class EntityKey : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string EntityContainerNameField;
        
        private System.Data.EntityKeyMember[] EntityKeyValuesField;
        
        private string EntitySetNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName
        {
            get
            {
                return this.EntityContainerNameField;
            }
            set
            {
                this.EntityContainerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.EntityKeyMember[] EntityKeyValues
        {
            get
            {
                return this.EntityKeyValuesField;
            }
            set
            {
                this.EntityKeyValuesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName
        {
            get
            {
                return this.EntitySetNameField;
            }
            set
            {
                this.EntitySetNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.Objects.DataClasses.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BJAirQuality.TB_Message[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BJAirQuality.TB_Message))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BJAirQuality.TB_RTC[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BJAirQuality.TB_RTC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BJAirQuality.TB_Alert[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BJAirQuality.TB_Alert))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Data.EntityKeyMember[]))]
    public partial class EntityKeyMember : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string KeyField;
        
        private object ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="DataService")]
public interface DataService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:DataService/GetWebCounts", ReplyAction="urn:DataService/GetWebCountsResponse")]
    string GetWebCounts();
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:DataService/GetWebCounts", ReplyAction="urn:DataService/GetWebCountsResponse")]
    System.Threading.Tasks.Task<string> GetWebCountsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:DataService/GetWebData", ReplyAction="urn:DataService/GetWebDataResponse")]
    string GetWebData();
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:DataService/GetWebData", ReplyAction="urn:DataService/GetWebDataResponse")]
    System.Threading.Tasks.Task<string> GetWebDataAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:DataService/GetWebAlert", ReplyAction="urn:DataService/GetWebAlertResponse")]
    string GetWebAlert();
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:DataService/GetWebAlert", ReplyAction="urn:DataService/GetWebAlertResponse")]
    System.Threading.Tasks.Task<string> GetWebAlertAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:DataService/GetWebPredict", ReplyAction="urn:DataService/GetWebPredictResponse")]
    string GetWebPredict();
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:DataService/GetWebPredict", ReplyAction="urn:DataService/GetWebPredictResponse")]
    System.Threading.Tasks.Task<string> GetWebPredictAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:DataService/DayForecast", ReplyAction="urn:DataService/DayForecastResponse")]
    BJAirQuality.TB_Message[] DayForecast();
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:DataService/DayForecast", ReplyAction="urn:DataService/DayForecastResponse")]
    System.Threading.Tasks.Task<BJAirQuality.TB_Message[]> DayForecastAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:DataService/GetRTC", ReplyAction="urn:DataService/GetRTCResponse")]
    BJAirQuality.TB_RTC[] GetRTC();
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:DataService/GetRTC", ReplyAction="urn:DataService/GetRTCResponse")]
    System.Threading.Tasks.Task<BJAirQuality.TB_RTC[]> GetRTCAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:DataService/GetRTC24h", ReplyAction="urn:DataService/GetRTC24hResponse")]
    BJAirQuality.TB_RTC[] GetRTC24h(string Station, string Pollutant);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:DataService/GetRTC24h", ReplyAction="urn:DataService/GetRTC24hResponse")]
    System.Threading.Tasks.Task<BJAirQuality.TB_RTC[]> GetRTC24hAsync(string Station, string Pollutant);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:DataService/GetAlert", ReplyAction="urn:DataService/GetAlertResponse")]
    BJAirQuality.TB_Alert[] GetAlert();
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:DataService/GetAlert", ReplyAction="urn:DataService/GetAlertResponse")]
    System.Threading.Tasks.Task<BJAirQuality.TB_Alert[]> GetAlertAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface DataServiceChannel : DataService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DataServiceClient : System.ServiceModel.ClientBase<DataService>, DataService
{
    
    public DataServiceClient()
    {
    }
    
    public DataServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetWebCounts()
    {
        return base.Channel.GetWebCounts();
    }
    
    public System.Threading.Tasks.Task<string> GetWebCountsAsync()
    {
        return base.Channel.GetWebCountsAsync();
    }
    
    public string GetWebData()
    {
        return base.Channel.GetWebData();
    }
    
    public System.Threading.Tasks.Task<string> GetWebDataAsync()
    {
        return base.Channel.GetWebDataAsync();
    }
    
    public string GetWebAlert()
    {
        return base.Channel.GetWebAlert();
    }
    
    public System.Threading.Tasks.Task<string> GetWebAlertAsync()
    {
        return base.Channel.GetWebAlertAsync();
    }
    
    public string GetWebPredict()
    {
        return base.Channel.GetWebPredict();
    }
    
    public System.Threading.Tasks.Task<string> GetWebPredictAsync()
    {
        return base.Channel.GetWebPredictAsync();
    }
    
    public BJAirQuality.TB_Message[] DayForecast()
    {
        return base.Channel.DayForecast();
    }
    
    public System.Threading.Tasks.Task<BJAirQuality.TB_Message[]> DayForecastAsync()
    {
        return base.Channel.DayForecastAsync();
    }
    
    public BJAirQuality.TB_RTC[] GetRTC()
    {
        return base.Channel.GetRTC();
    }
    
    public System.Threading.Tasks.Task<BJAirQuality.TB_RTC[]> GetRTCAsync()
    {
        return base.Channel.GetRTCAsync();
    }
    
    public BJAirQuality.TB_RTC[] GetRTC24h(string Station, string Pollutant)
    {
        return base.Channel.GetRTC24h(Station, Pollutant);
    }
    
    public System.Threading.Tasks.Task<BJAirQuality.TB_RTC[]> GetRTC24hAsync(string Station, string Pollutant)
    {
        return base.Channel.GetRTC24hAsync(Station, Pollutant);
    }
    
    public BJAirQuality.TB_Alert[] GetAlert()
    {
        return base.Channel.GetAlert();
    }
    
    public System.Threading.Tasks.Task<BJAirQuality.TB_Alert[]> GetAlertAsync()
    {
        return base.Channel.GetAlertAsync();
    }
}
